version: '2'
services:
  db_webapp:
    container_name: "db_webapp"
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=db_webapp
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 4444:3306
  team_error_webapp:
    container_name: "team_error_webapp"
    build: ./webApp
    ports:
      - 8740:8080
      - 8741:9990

    depends_on:
      - db_webapp


  db_reportsmodule:
     container_name: "db_reportsmodule"
     image: mysql:latest
     environment:
       - MYSQL_DATABASE=db_reportsmodule
       - MYSQL_USER=mysql
       - MYSQL_PASSWORD=mysql
       - MYSQL_ROOT_PASSWORD=pass
     ports:
       - 4445:3306
  reports_module:
     container_name: "reportsmodule"
     build: ./reportsModule
     ports:
       - 8742:8080
       - 8743:9990

     depends_on:
       - db_reportsmodule